/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-pedidos",
  template: `
    <main class="flex overflow-hidden flex-col bg-white">
      <header
        class="flex flex-col items-center pb-11 w-full bg-stone-300 max-md:max-w-full"
      >
        <nav
          class="flex flex-wrap gap-10 self-stretch px-20 py-4 w-full text-3xl font-bold text-white whitespace-nowrap bg-neutral-700 max-md:px-5 max-md:max-w-full"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3692280d6223ba6f898472bfaa513a16c1b8bbc94ff8b5798adb69fafd1d7611?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
            alt=""
            class="object-contain shrink-0 max-w-full aspect-square w-[110px]"
          />
          <div class="flex gap-10 my-auto max-md:max-w-full">
            <h1 class="grow font-extrabold">Pedidos</h1>
            <a href="#inventario">Inventario</a>
            <a href="#foro">Foro</a>
            <a href="#perfil">Perfil</a>
          </div>
        </nav>
        <section
          class="flex flex-wrap gap-8 mt-9 w-full max-w-[1289px] max-md:max-w-full"
        >
          <button
            class="px-10 py-4 text-3xl font-bold text-white whitespace-nowrap bg-amber-300 rounded-[50px] max-md:px-5"
          >
            Filtros
          </button>
          <div
            class="flex flex-col grow shrink-0 justify-center items-start px-8 py-5 basis-0 bg-neutral-800 rounded-[50px] w-fit max-md:px-5 max-md:max-w-full"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/bcc636790325e37c17ece7d9aa2189bf8e8895fdb7a7ffd8626793eaffed18c3?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
              alt=""
              class="object-contain aspect-[1.13] w-[34px]"
            />
          </div>
        </section>
        <section
          class="flex flex-wrap gap-10 mt-14 w-full max-w-[1325px] max-md:mt-10 max-md:max-w-full"
        >
          <div
            class="flex flex-col grow shrink-0 self-start mt-2.5 basis-0 w-fit max-md:max-w-full"
          >
            <div class="w-full max-md:max-w-full">
              <div class="flex gap-5 max-md:flex-col">
                <div class="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                  <div class="grow max-md:mt-3.5 max-md:max-w-full">
                    <div class="flex gap-5 max-md:flex-col">
                      <div
                        class="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6225d25554832b5ce70c081a38745474c8bed94fb6254a200e53c787231f3617?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Collares cerámica"
                          class="object-contain w-full aspect-square"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <article
                          class="flex flex-col px-7 py-3 w-full text-3xl bg-white max-md:px-5"
                        >
                          <div class="mr-6 text-black w-[259px] max-md:mr-2.5">
                            <span class="text-5xl">10/10</span>
                            <br />
                            <time class="text-4xl">02/09/24</time>
                            <br />
                            Collares cerámica
                            <br />
                            Juan Pérez
                          </div>
                          <button
                            class="self-start px-16 py-3.5 mt-11 ml-2.5 font-bold text-white whitespace-nowrap bg-red-400 rounded-[50px] max-md:px-5 max-md:mt-10"
                          >
                            Revisar
                          </button>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full"
                >
                  <div class="grow max-md:mt-3.5 max-md:max-w-full">
                    <div class="flex gap-5 max-md:flex-col">
                      <div
                        class="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/98a2a5a6d029a3fecacb07fe5980caafd2fe0b55c803e4626cc6d893ca6ca8eb?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Tipo 1"
                          class="object-contain w-full aspect-square"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <article
                          class="flex flex-col items-start px-7 py-3 w-full text-3xl bg-white max-md:px-5"
                        >
                          <div class="text-black w-[259px]">
                            <span class="text-5xl">8/31</span>
                            <br />
                            <time class="text-4xl">00:10:00:00</time>
                            <br />
                            Tipo 1
                            <br />
                            Mario Juárez
                          </div>
                          <button
                            class="px-16 py-4 mt-11 ml-2.5 w-60 max-w-full font-bold text-white whitespace-nowrap bg-red-400 rounded-[50px] max-md:px-5 max-md:mt-10"
                          >
                            Revisar
                          </button>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="mt-8 w-full max-md:max-w-full">
              <div class="flex gap-5 max-md:flex-col">
                <div class="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                  <div class="grow max-md:mt-3.5 max-md:max-w-full">
                    <div class="flex gap-5 max-md:flex-col">
                      <div
                        class="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fb6913de68dcbafd36f962174a3769736ec43797e214be67101cb157453378e6?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Regalo Cumpleaños"
                          class="object-contain w-full aspect-square"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <article
                          class="flex flex-col px-7 pt-1.5 pb-4 w-full text-3xl bg-white max-md:pl-5"
                        >
                          <div class="text-black">
                            <span class="text-5xl">0/1</span>
                            <br />
                            <time class="text-4xl">01:13:02:00</time>
                            <br />
                            Regalo Cumpleaños
                            <br />
                            Rosario Libertad
                          </div>
                          <button
                            class="px-16 py-4 mt-11 ml-2.5 w-60 max-w-full font-bold text-white whitespace-nowrap bg-red-400 rounded-[50px] max-md:px-5 max-md:mt-10 max-md:mr-2.5"
                          >
                            Revisar
                          </button>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full"
                >
                  <div class="grow max-md:mt-3.5 max-md:max-w-full">
                    <div class="flex gap-5 max-md:flex-col">
                      <div
                        class="flex flex-col w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4fca5c4be440e4c07fcee5cf15b1d9baa7fac58da67de82c2027c3f65adbdeb3?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Pedido Especial"
                          class="object-contain w-full aspect-square"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full"
                      >
                        <article
                          class="flex flex-col items-start px-7 pt-1.5 pb-4 w-full text-3xl bg-white max-md:px-5"
                        >
                          <div class="text-black w-[259px]">
                            <span class="text-5xl">22/50</span>
                            <br />
                            <time class="text-4xl">00:08:03:04</time>
                            <br />
                            Pedido Especial
                            <br />
                            George Takumi
                          </div>
                          <button
                            class="px-16 py-4 mt-11 ml-2.5 w-60 max-w-full font-bold text-white whitespace-nowrap bg-red-400 rounded-[50px] max-md:px-5 max-md:mt-10"
                          >
                            Revisar
                          </button>
                        </article>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <aside
            class="flex flex-col px-1.5 pt-2 bg-white pb-[562px] max-md:hidden max-md:pb-24"
          >
            <div class="flex shrink-0 bg-red-400 h-[111px]"></div>
          </aside>
        </section>
      </header>
    </main>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class PedidosComponent {}
