/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { PedidosComponent } from "./PedidosComponent";

@NgModule({
  declarations: [PedidosComponent],
  imports: [CommonModule],
  exports: [PedidosComponent],
})
export class PedidosModule {}
