/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-my-component",
  template: `
    <div class="flex overflow-hidden flex-col bg-white">
      <header class="flex flex-col pb-16 w-full bg-stone-300 max-md:max-w-full">
        <nav
          class="flex flex-wrap gap-10 px-20 py-4 w-full text-3xl font-bold text-white whitespace-nowrap bg-neutral-700 max-md:px-5 max-md:max-w-full"
        >
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3692280d6223ba6f898472bfaa513a16c1b8bbc94ff8b5798adb69fafd1d7611?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
            alt=""
            class="object-contain shrink-0 max-w-full aspect-square w-[110px]"
          />
          <div class="flex gap-10 my-auto max-md:max-w-full">
            <a href="#" class="basis-auto">Pedidos</a>
            <a href="#" class="basis-auto">Distribución</a>
            <a href="#" class="basis-auto">Foro</a>
            <a href="#" class="basis-auto">Perfil</a>
          </div>
        </nav>
        <main
          class="flex flex-col items-start self-center pt-9 pr-3 pb-3.5 pl-12 mt-14 w-full bg-white max-w-[1214px] max-md:pl-5 max-md:mt-10 max-md:max-w-full"
        >
          <section class="self-stretch max-md:max-w-full">
            <div class="flex gap-5 max-md:flex-col">
              <div class="flex flex-col w-[19%] max-md:ml-0 max-md:w-full">
                <div
                  class="flex flex-col grow items-start text-black max-md:mt-5"
                >
                  <button
                    class="px-9 py-3.5 text-3xl font-bold text-white whitespace-nowrap bg-red-500 rounded-[50px] max-md:px-5"
                  >
                    Volver
                  </button>
                  <h2 class="mt-5 text-4xl">Fotos</h2>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/fa1eb827b5896946e3ffe4b7678577091a6fe1be65c7764f3bcc59e60f9246d9?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                    alt="Product photo"
                    class="object-contain mt-2.5 aspect-square w-[200px]"
                  />
                  <div class="self-stretch mt-6 text-7xl max-md:text-4xl">
                    10 / 10
                  </div>
                </div>
              </div>
              <div class="flex flex-col ml-5 w-[81%] max-md:ml-0 max-md:w-full">
                <div class="flex flex-col w-full max-md:mt-5 max-md:max-w-full">
                  <div class="flex flex-wrap gap-9 w-full max-md:max-w-full">
                    <div
                      class="flex flex-col grow shrink-0 self-start text-5xl text-black basis-0 w-fit max-md:max-w-full max-md:text-4xl"
                    >
                      <h1 class="self-start max-md:text-4xl">
                        Collares cerámica
                      </h1>
                      <div
                        class="shrink-0 h-px border border-black border-solid max-md:max-w-full"
                      ></div>
                    </div>
                    <div class="flex flex-auto gap-2.5 font-bold">
                      <button
                        class="px-3.5 py-4 text-3xl text-white whitespace-nowrap bg-red-500 rounded-[50px]"
                      >
                        Aceptar
                      </button>
                      <div
                        class="px-3.5 py-5 text-2xl text-black bg-amber-200 rounded-[50px]"
                      >
                        En Progreso
                      </div>
                    </div>
                  </div>
                  <div
                    class="mt-20 max-md:mt-10 max-md:mr-2.5 max-md:max-w-full"
                  >
                    <div class="flex gap-5 max-md:flex-col">
                      <div
                        class="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/56086737dbfe7ea57ecefa5634b0106a13b3b5d057ea5eb1f9a9a473467e59aa?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Product image 1"
                          class="object-contain shrink-0 max-w-full aspect-square w-[200px] max-md:mt-9"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/8264316e310c4ed85b78a5d573c4cf8268af482e67d205edbc210a7d0d65d2b8?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Product image 2"
                          class="object-contain shrink-0 max-w-full aspect-square w-[200px] max-md:mt-9"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/31f8d411a7e8079211ad122ea25a58da0fe8d8e6bb92e3103dc4a148012f64b1?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Product image 3"
                          class="object-contain shrink-0 max-w-full aspect-square w-[200px] max-md:mt-9"
                        />
                      </div>
                      <div
                        class="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full"
                      >
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/adac4dfb250e3d4414be65cbe4c6f5806c312182f861054afb325a4b44837d1a?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                          alt="Product image 4"
                          class="object-contain shrink-0 max-w-full aspect-square w-[200px] max-md:mt-9"
                        />
                      </div>
                    </div>
                  </div>
                  <div
                    class="self-center mt-7 ml-14 text-6xl text-black max-md:max-w-full max-md:text-4xl"
                  >
                    00:00:00:00 restante
                  </div>
                </div>
              </div>
            </div>
          </section>
          <h3 class="mt-2.5 text-4xl text-black max-md:max-w-full">
            Comentario para el artesano:
            <span class="italic">Joaquín Esquerre</span>
          </h3>
          <div
            class="flex flex-col pt-4 pr-20 pb-1.5 pl-7 mt-4 w-full text-3xl bg-amber-200 max-w-[1100px] rounded-[50px] max-md:px-5 max-md:max-w-full"
          >
            <p class="self-start text-black max-md:max-w-full">
              (Hace 2 horas) Se ven bien, No tengo cambios que solicitar.
            </p>
            <button
              class="flex gap-7 self-center px-4 py-1 mt-16 max-w-full font-bold text-white bg-red-400 rounded-[50px] w-[405px] max-md:mt-10"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/adfb2ee1664150049cbf9662ab585b4caf088ef1582fba989eb91c76fadaca75?placeholderIfAbsent=true&apiKey=9739142c15cf443ab3377e4fb9a90ea3"
                alt=""
                class="object-contain shrink-0 aspect-[0.98] w-[59px]"
              />
              <span class="flex-auto my-auto w-[274px]">Nuevo Comentario</span>
            </button>
          </div>
        </main>
      </header>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class MyComponentComponent {}
